/**
 * The writing section — build-time only.
 *
 * Posts are markdown files in `src/writing/`. This module renders them to
 * static HTML during `vite build` and emits an index, a page per post, and an
 * RSS feed. Nothing here ships to the browser: `marked`, `gray-matter` and
 * `highlight.js` are devDependencies and the site's runtime `dependencies`
 * stays empty, which is the property worth protecting.
 *
 * Pages are emitted rather than declared as Vite inputs because the set of
 * posts is discovered from disk — a rollupOptions.input map would have to be
 * regenerated by hand for every new post, which is exactly the friction that
 * stops people writing.
 */

import fs from 'node:fs';
import path from 'node:path';
import matter from 'gray-matter';
import { Marked } from 'marked';
import hljs from 'highlight.js';

const POSTS_DIR = 'src/writing';
const SITE = 'https://josephharveyangeles.com';
const AUTHOR = 'Joseph Harvey Angeles';

const marked = new Marked({
  gfm: true,
  breaks: false,
  renderer: {
    code({ text, lang }) {
      const language = lang && hljs.getLanguage(lang) ? lang : null;
      const html = language
        ? hljs.highlight(text, { language }).value
        : escapeHtml(text);
      const cls = language ? ` class="language-${language}"` : '';
      return `<pre><code${cls}>${html}</code></pre>\n`;
    },
  },
});

function escapeHtml(s) {
  return s
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#39;');
}

/** `2026-08-02` -> `2 August 2026`, in the site's editorial register. */
function longDate(iso) {
  const d = new Date(`${iso}T00:00:00Z`);
  return new Intl.DateTimeFormat('en-GB', {
    day: 'numeric',
    month: 'long',
    year: 'numeric',
    timeZone: 'UTC',
  }).format(d);
}

/**
 * Read every post. `draft: true` posts are readable in `vite dev` so they can
 * be previewed, and dropped from a production build so a half-written piece
 * cannot ship by accident.
 */
export function loadPosts({ includeDrafts = false } = {}) {
  if (!fs.existsSync(POSTS_DIR)) return [];

  return fs
    .readdirSync(POSTS_DIR)
    .filter(f => f.endsWith('.md'))
    .map(file => {
      const raw = fs.readFileSync(path.join(POSTS_DIR, file), 'utf8');
      const { data, content } = matter(raw);
      const slug = data.slug || file.replace(/\.md$/, '');

      if (!data.title) throw new Error(`${file}: front-matter needs a title`);
      if (!data.date) throw new Error(`${file}: front-matter needs a date`);

      return {
        slug,
        title: data.title,
        date: data.date instanceof Date
          ? data.date.toISOString().slice(0, 10)
          : String(data.date),
        description: data.description || '',
        draft: Boolean(data.draft),
        body: marked.parse(content),
      };
    })
    .filter(p => includeDrafts || !p.draft)
    .sort((a, b) => (a.date < b.date ? 1 : -1));
}

/* ---------------------------------------------------------------- templates */

/**
 * The chrome every page shares. Kept in one place so the writing pages cannot
 * drift from the homepage's masthead, theme handling or font loading.
 */
function shell({ title, description, canonical, cssHref, jsHref, body }) {
  return `<!doctype html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>${escapeHtml(title)}</title>

    <!-- Resolve the theme before first paint so there is no flash. -->
    <script>
      (function () {
        try {
          var stored = localStorage.getItem('theme');
          var theme =
            stored === 'light' || stored === 'dark'
              ? stored
              : window.matchMedia('(prefers-color-scheme: light)').matches
                ? 'light'
                : 'dark';
          document.documentElement.setAttribute('data-theme', theme);
        } catch (e) {
          document.documentElement.setAttribute('data-theme', 'dark');
        }
      })();
    </script>

    <meta name="description" content="${escapeHtml(description)}" />
    <meta name="author" content="${AUTHOR}" />
    <link rel="canonical" href="${canonical}" />
    <link rel="alternate" type="application/rss+xml" title="${AUTHOR} — Writing" href="${SITE}/rss.xml" />

    <meta property="og:type" content="article" />
    <meta property="og:title" content="${escapeHtml(title)}" />
    <meta property="og:description" content="${escapeHtml(description)}" />
    <meta property="og:url" content="${canonical}" />
    <meta property="og:image" content="${SITE}/og-image.png" />
    <meta name="twitter:card" content="summary_large_image" />
    <meta name="twitter:title" content="${escapeHtml(title)}" />
    <meta name="twitter:description" content="${escapeHtml(description)}" />
    <meta name="twitter:image" content="${SITE}/og-image.png" />

    <meta name="theme-color" content="#1c1a17" media="(prefers-color-scheme: dark)" />
    <meta name="theme-color" content="#f4f1ea" media="(prefers-color-scheme: light)" />

    <link rel="icon" href="/favicon.ico" sizes="any" />
    <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png" />
    <link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png" />

    <link rel="preload" href="/fonts/newsreader-latin.woff2" as="font" type="font/woff2" crossorigin />
    <link rel="preload" href="/fonts/jetbrains-mono-latin.woff2" as="font" type="font/woff2" crossorigin />

    <link rel="stylesheet" href="${cssHref}" />
  </head>

  <body>
    <div class="wrap">
      <header class="masthead mono">
        <div class="masthead-left">
          <span class="pmark" aria-hidden="true"></span>
          <a class="masthead-home" href="/">${AUTHOR}</a>
        </div>
        <button class="theme-toggle" id="themeToggle" type="button" aria-live="polite">
          <span id="themeLabel">Day edition</span>
        </button>
      </header>

      <main>
${body}
      </main>

      <footer class="colophon mono">
        <a href="/">← Back to the site</a>
      </footer>
    </div>
    <script type="module" src="${jsHref}"></script>
  </body>
</html>
`;
}

function indexBody(posts) {
  const items = posts.length
    ? posts
        .map(
          p => `          <li class="writing-item">
            <div class="mono writing-date">${longDate(p.date)}</div>
            <h2 class="writing-title">
              <a href="/writing/${p.slug}/">${escapeHtml(p.title)}</a>
            </h2>
            ${p.description ? `<p class="writing-excerpt muted">${escapeHtml(p.description)}</p>` : ''}
          </li>`
        )
        .join('\n')
    : `          <li class="writing-item">
            <p class="muted">Nothing published yet.</p>
          </li>`;

  return `        <section class="section writing-index">
          <div class="row">
            <div class="gutter">
              <div class="numeral" aria-hidden="true">§</div>
              <div class="mono kicker">Writing</div>
            </div>
            <div class="col">
              <h1 class="section-title">Writing</h1>
              <p class="muted">
                Notes on the parts of the work that were hard enough to be
                worth writing down.
              </p>
              <ul class="writing-list">
${items}
              </ul>
            </div>
          </div>
        </section>`;
}

function postBody(post) {
  return `        <article class="section post">
          <div class="row">
            <div class="gutter">
              <div class="mono writing-date">${longDate(post.date)}</div>
            </div>
            <div class="col">
              <h1 class="post-title">${escapeHtml(post.title)}</h1>
              <div class="post-body">
${post.body}
              </div>
            </div>
          </div>
        </article>`;
}

function rss(posts) {
  const items = posts
    .map(
      p => `    <item>
      <title>${escapeHtml(p.title)}</title>
      <link>${SITE}/writing/${p.slug}/</link>
      <guid isPermaLink="true">${SITE}/writing/${p.slug}/</guid>
      <pubDate>${new Date(`${p.date}T00:00:00Z`).toUTCString()}</pubDate>
      <description>${escapeHtml(p.description)}</description>
    </item>`
    )
    .join('\n');

  return `<?xml version="1.0" encoding="UTF-8"?>
<rss version="2.0" xmlns:atom="http://www.w3.org/2005/Atom">
  <channel>
    <title>${AUTHOR} — Writing</title>
    <link>${SITE}/writing/</link>
    <description>Notes on the parts of the work that were hard enough to be worth writing down.</description>
    <language>en</language>
    <atom:link href="${SITE}/rss.xml" rel="self" type="application/rss+xml" />
${items}
  </channel>
</rss>
`;
}

/* ------------------------------------------------------------------- plugin */

export function writingPlugin() {
  let isBuild = false;

  return {
    name: 'writing',

    configResolved(config) {
      isBuild = config.command === 'build';
    },

    /** Latest three posts on the homepage. */
    transformIndexHtml(html) {
      const posts = loadPosts({ includeDrafts: !isBuild }).slice(0, 3);
      const list = posts.length
        ? posts
            .map(
              p => `                <li class="writing-item">
                  <div class="mono writing-date">${longDate(p.date)}</div>
                  <h3 class="writing-title">
                    <a href="/writing/${p.slug}/">${escapeHtml(p.title)}</a>
                  </h3>
                </li>`
            )
            .join('\n')
        : '';

      // With nothing published, drop the entire section — heading, numeral and
      // all. A section title with no content under it reads as broken, and the
      // scaffolded state of this feature is "ready", not "empty".
      if (!posts.length) {
        return html.replace(
          /<!-- WRITING_SECTION_START -->[\s\S]*?<!-- WRITING_SECTION_END -->\n?/,
          ''
        );
      }

      const section = `<ul class="writing-list">\n${list}\n              </ul>
              <p class="writing-more">
                <a href="/writing/">All writing →</a>
              </p>`;

      return html
        .replace('<!-- WRITING_POSTS -->', section)
        .replace('<!-- WRITING_SECTION_START -->\n', '')
        .replace('<!-- WRITING_SECTION_END -->\n', '');
    },

    /**
     * Written in `writeBundle`, not `generateBundle`, and the asset paths are
     * read back out of the finished `index.html` rather than guessed from the
     * bundle. The chunk names visible during generateBundle are not the final
     * filenames — an earlier version of this emitted pages pointing at a
     * `main-*.js` that never existed on disk, so the theme toggle and clock
     * were silently dead on every writing page. Reading the real homepage
     * makes it impossible for these pages to reference anything it doesn't.
     */
    writeBundle(options) {
      const outDir = options.dir;
      const home = fs.readFileSync(path.join(outDir, 'index.html'), 'utf8');

      const cssHref = (home.match(/href="([^"]+\.css)"/) || [])[1];
      const jsHref = (home.match(/src="([^"]+\.js)"/) || [])[1];
      if (!cssHref || !jsHref) {
        this.error('writing: could not find the built CSS/JS in index.html');
      }

      const posts = loadPosts();
      const write = (rel, source) => {
        const file = path.join(outDir, rel);
        fs.mkdirSync(path.dirname(file), { recursive: true });
        fs.writeFileSync(file, source);
      };

      write(
        'writing/index.html',
        shell({
          title: `Writing — ${AUTHOR}`,
          description:
            'Notes on the parts of the work that were hard enough to be worth writing down.',
          canonical: `${SITE}/writing/`,
          cssHref,
          jsHref,
          body: indexBody(posts),
        })
      );

      for (const post of posts) {
        write(
          `writing/${post.slug}/index.html`,
          shell({
            title: `${post.title} — ${AUTHOR}`,
            description: post.description,
            canonical: `${SITE}/writing/${post.slug}/`,
            cssHref,
            jsHref,
            body: postBody(post),
          })
        );
      }

      write('rss.xml', rss(posts));
    },
  };
}
